name: Fail Workflow 1

on:
  push:
    branches: [ main ]

jobs:
  intentional-fail-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step that fails 1
        run: exit 1
      - name: This step will not run
        run: echo "Should not see this"
