name: Fail Workflow 4

on:
  push:
    branches: [ main ]

jobs:
  intentional-fail-job-4:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step in Job 1
        run: |
          echo "This is Job 1"
          exit 1

  intentional-fail-job-4_1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step in Job 2
        run: |
          echo "This is Job 2"
          exit 1
