name: Fail Workflow 3

on:
  workflow_dispatch:

jobs:
  double-failure:
    runs-on: ubuntu-latest
    steps:
      - name: First failing step
        run: exit 1
        continue-on-error: true

      - name: Second failing step
        run: exit 1
        continue-on-error: true
