name: Fail Workflow 3

on:
  push:
    branches: [ main ]

jobs:
  intentional-fail-job-3:
    runs-on: ubuntu-latest
    steps:
      - name: First failing step
        run: exit 1

      - name: Second failing step
        run: exit 1
